// <auto-generated />
using System;
using ComicSort.Data.SQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComicSort.Data.Migrations
{
    [DbContext(typeof(ComicSortDBSQLiteContext))]
    [Migration("20260111020215_AddComicInfo")]
    partial class AddComicInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("ComicSort.Data.Entities.ComicBookEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.ToTable("ComicBooks", (string)null);
                });

            modelBuilder.Entity("ComicSort.Data.Entities.ComicInfoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlternateSeries")
                        .HasColumnType("TEXT");

                    b.Property<string>("Characters")
                        .HasColumnType("TEXT");

                    b.Property<string>("Colorist")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ComicBookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverArtist")
                        .HasColumnType("TEXT");

                    b.Property<string>("Editor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Inker")
                        .HasColumnType("TEXT");

                    b.Property<string>("Letterer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Locations")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Penciller")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.Property<string>("Series")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Teams")
                        .HasColumnType("TEXT");

                    b.Property<string>("Writer")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComicBookId")
                        .IsUnique();

                    b.ToTable("ComicInfo", (string)null);
                });

            modelBuilder.Entity("ComicSort.Data.Entities.ComicInfoPageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ComicInfoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Image")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImageHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImageWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComicInfoId", "Image")
                        .IsUnique();

                    b.ToTable("ComicInfoPages", (string)null);
                });

            modelBuilder.Entity("ComicSort.Data.Entities.ComicInfoEntity", b =>
                {
                    b.HasOne("ComicSort.Data.Entities.ComicBookEntity", "ComicBook")
                        .WithOne("ComicInfo")
                        .HasForeignKey("ComicSort.Data.Entities.ComicInfoEntity", "ComicBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComicBook");
                });

            modelBuilder.Entity("ComicSort.Data.Entities.ComicInfoPageEntity", b =>
                {
                    b.HasOne("ComicSort.Data.Entities.ComicInfoEntity", "ComicInfo")
                        .WithMany("Pages")
                        .HasForeignKey("ComicInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComicInfo");
                });

            modelBuilder.Entity("ComicSort.Data.Entities.ComicBookEntity", b =>
                {
                    b.Navigation("ComicInfo");
                });

            modelBuilder.Entity("ComicSort.Data.Entities.ComicInfoEntity", b =>
                {
                    b.Navigation("Pages");
                });
#pragma warning restore 612, 618
        }
    }
}
