// <auto-generated />
using System;
using ComicSort.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComicSort.DataAccess.Migrations
{
    [DbContext(typeof(ComicDBContext))]
    [Migration("20210514224259_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("ComicSort.Domain.Models.ComicBook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ComicBookListId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("File")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssueNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PagesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Series")
                        .HasColumnType("TEXT");

                    b.Property<string>("Volume")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComicBookListId");

                    b.HasIndex("PagesId");

                    b.ToTable("ComicBooks");
                });

            modelBuilder.Entity("ComicSort.Domain.Models.ComicBookList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ComicBookLists");
                });

            modelBuilder.Entity("ComicSort.Domain.Models.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Image")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ImageHeight")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ImageWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("ComicSort.Domain.Models.ComicBook", b =>
                {
                    b.HasOne("ComicSort.Domain.Models.ComicBookList", null)
                        .WithMany("ComicBooks")
                        .HasForeignKey("ComicBookListId");

                    b.HasOne("ComicSort.Domain.Models.Page", "Pages")
                        .WithMany()
                        .HasForeignKey("PagesId");

                    b.Navigation("Pages");
                });

            modelBuilder.Entity("ComicSort.Domain.Models.ComicBookList", b =>
                {
                    b.Navigation("ComicBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
